# PlayerVaultsDupePatch by Terrobility
# Skype: huntergplays and Spigot: Terrobility <3
#
# x=x=x=x=x=x=x=x=x
# | CONFIGURATION |
# x=x=x=x=x=x=x=x=x
# Please don't change the config version.
config-version: 3

message:
- "&cYou dun goofed!"
